import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { LighthouseReport } from "@/types/report";

function isValidReport(report: LighthouseReport): boolean {
  if (report.error) return false;
  const { performance, accessibility, seo, bestPractices } = report.scores;
  if (
    performance === 0 &&
    accessibility === 0 &&
    seo === 0 &&
    bestPractices === 0
  ) {
    return false;
  }
  return true;
}

function getScoreColor(score: number): [number, number, number] {
  if (score >= 90) return [0, 128, 0];
  if (score >= 50) return [255, 165, 0];
  return [255, 0, 0];
}

function getScoreBgColor(score: number): [number, number, number] {
  if (score >= 90) return [220, 252, 231]; // light green
  if (score >= 50) return [254, 243, 199]; // light amber
  return [254, 226, 226]; // light red
}

function getScoreLabel(score: number): string {
  if (score >= 90) return "Good";
  if (score >= 50) return "Needs Work";
  return "Poor";
}

function drawHeaderBar(doc: jsPDF): void {
  const pageWidth = doc.internal.pageSize.getWidth();
  doc.setFillColor(30, 41, 82); // dark indigo
  doc.rect(0, 0, pageWidth, 18, "F");

  // Accent stripe
  doc.setFillColor(79, 70, 229); // indigo-600
  doc.rect(0, 18, pageWidth, 2, "F");

  doc.setFontSize(10);
  doc.setTextColor(255, 255, 255);
  doc.text("Lighthouse Bulk Reporter", 14, 12);

  const dateStr = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  doc.setFontSize(8);
  doc.text(dateStr, pageWidth - 14, 12, { align: "right" });
}

function drawFooter(doc: jsPDF, pageNumber: number, totalPages: number): void {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // Footer line
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.5);
  doc.line(14, pageHeight - 15, pageWidth - 14, pageHeight - 15);

  doc.setFontSize(7);
  doc.setTextColor(140, 140, 140);
  doc.text("Generated by Lighthouse Bulk Reporter", 14, pageHeight - 9);
  doc.text(
    `Page ${pageNumber} of ${totalPages}`,
    pageWidth - 14,
    pageHeight - 9,
    { align: "right" }
  );
}

function drawSectionDivider(doc: jsPDF, y: number): number {
  const pageWidth = doc.internal.pageSize.getWidth();
  doc.setDrawColor(79, 70, 229); // indigo
  doc.setLineWidth(0.8);
  doc.line(14, y, pageWidth - 14, y);
  return y + 6;
}

interface JsPDFWithAutoTable extends jsPDF {
  lastAutoTable?: { finalY: number };
  previousAutoTable?: { finalY: number };
}

export function exportPDF(reports: LighthouseReport[]): void {
  try {
  const validReports = reports.filter(isValidReport);

  if (validReports.length === 0) {
    return;
  }

  const doc: JsPDFWithAutoTable = new jsPDF({ orientation: "landscape" });
  const today = new Date().toISOString().split("T")[0];
  const pageWidth = doc.internal.pageSize.getWidth();

  // Draw header bar on first page
  drawHeaderBar(doc);

  // Title section
  doc.setFontSize(22);
  doc.setTextColor(30, 41, 82);
  doc.text("Lighthouse Performance Report", 14, 34);

  doc.setFontSize(10);
  doc.setTextColor(120, 120, 120);
  doc.text(
    `Generated on ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}  |  ${validReports.length} URLs analyzed`,
    14,
    42
  );

  // Summary section
  const avgPerformance =
    validReports.reduce((sum, r) => sum + r.scores.performance, 0) /
    validReports.length;
  const avgAccessibility =
    validReports.reduce((sum, r) => sum + r.scores.accessibility, 0) /
    validReports.length;
  const avgSEO =
    validReports.reduce((sum, r) => sum + r.scores.seo, 0) /
    validReports.length;
  const avgBestPractices =
    validReports.reduce((sum, r) => sum + r.scores.bestPractices, 0) /
    validReports.length;

  let currentY = drawSectionDivider(doc, 48);

  // Visual summary boxes
  doc.setFontSize(13);
  doc.setTextColor(30, 41, 82);
  doc.text("Average Scores", 14, currentY + 6);
  currentY += 14;

  const boxWidth = 58;
  const boxHeight = 28;
  const boxGap = 8;
  const startX = 14;
  const averages = [
    { label: "Performance", value: avgPerformance },
    { label: "Accessibility", value: avgAccessibility },
    { label: "SEO", value: avgSEO },
    { label: "Best Practices", value: avgBestPractices },
  ];

  averages.forEach((avg, i) => {
    const x = startX + i * (boxWidth + boxGap);
    const [bgR, bgG, bgB] = getScoreBgColor(Math.round(avg.value));
    const [txtR, txtG, txtB] = getScoreColor(Math.round(avg.value));

    // Box background
    doc.setFillColor(bgR, bgG, bgB);
    doc.roundedRect(x, currentY, boxWidth, boxHeight, 3, 3, "F");

    // Border
    doc.setDrawColor(txtR, txtG, txtB);
    doc.setLineWidth(0.6);
    doc.roundedRect(x, currentY, boxWidth, boxHeight, 3, 3, "S");

    // Score value
    doc.setFontSize(16);
    doc.setTextColor(txtR, txtG, txtB);
    doc.text(avg.value.toFixed(1), x + boxWidth / 2, currentY + 12, {
      align: "center",
    });

    // Label
    doc.setFontSize(8);
    doc.setTextColor(80, 80, 80);
    doc.text(avg.label, x + boxWidth / 2, currentY + 19, { align: "center" });

    // Rating label
    doc.setFontSize(7);
    doc.setTextColor(txtR, txtG, txtB);
    doc.text(
      getScoreLabel(Math.round(avg.value)),
      x + boxWidth / 2,
      currentY + 25,
      { align: "center" }
    );
  });

  currentY += boxHeight + 10;
  currentY = drawSectionDivider(doc, currentY);

  // Main scores table
  doc.setFontSize(13);
  doc.setTextColor(30, 41, 82);
  doc.text("Scores Overview", 14, currentY + 6);
  currentY += 12;

  const scoreColumns = ["URL", "Perf", "A11y", "SEO", "BP"];
  const scoreRows = validReports.map((report) => [
    report.url.length > 50 ? report.url.substring(0, 47) + "..." : report.url,
    String(report.scores.performance),
    String(report.scores.accessibility),
    String(report.scores.seo),
    String(report.scores.bestPractices),
  ]);

  autoTable(doc, {
    startY: currentY,
    head: [scoreColumns],
    body: scoreRows,
    theme: "grid",
    headStyles: {
      fillColor: [30, 41, 82],
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 9,
      cellPadding: 4,
    },
    bodyStyles: {
      fontSize: 8,
      cellPadding: 3,
    },
    alternateRowStyles: {
      fillColor: [245, 247, 250],
    },
    columnStyles: {
      0: { cellWidth: 100 },
      1: { cellWidth: 25, halign: "center" },
      2: { cellWidth: 25, halign: "center" },
      3: { cellWidth: 25, halign: "center" },
      4: { cellWidth: 25, halign: "center" },
    },
    didParseCell(data) {
      if (data.section === "body" && data.column.index >= 1) {
        const score = parseInt(data.cell.raw as string, 10);
        if (!isNaN(score)) {
          const [r, g, b] = getScoreColor(score);
          const [bgR, bgG, bgB] = getScoreBgColor(score);
          data.cell.styles.textColor = [r, g, b];
          data.cell.styles.fillColor = [bgR, bgG, bgB];
          data.cell.styles.fontStyle = "bold";
        }
      }
    },
    didDrawPage() {
      drawHeaderBar(doc);
    },
  });

  // Core Web Vitals section
  const lastTableY: number =
    doc.lastAutoTable?.finalY ?? doc.previousAutoTable?.finalY ?? 120;

  currentY = lastTableY + 12;

  if (currentY > 160) {
    doc.addPage();
    drawHeaderBar(doc);
    currentY = 28;
  }

  currentY = drawSectionDivider(doc, currentY);

  doc.setFontSize(13);
  doc.setTextColor(30, 41, 82);
  doc.text("Core Web Vitals", 14, currentY + 6);
  currentY += 12;

  const vitalsColumns = ["URL", "FCP", "LCP", "TBT", "CLS", "TTI", "Strategy"];
  const vitalsRows = validReports.map((report) => [
    report.url.length > 40 ? report.url.substring(0, 37) + "..." : report.url,
    report.coreWebVitals.fcp.displayValue,
    report.coreWebVitals.lcp.displayValue,
    report.coreWebVitals.tbt.displayValue,
    report.coreWebVitals.cls.displayValue,
    report.coreWebVitals.tti.displayValue,
    report.strategy,
  ]);

  autoTable(doc, {
    startY: currentY,
    head: [vitalsColumns],
    body: vitalsRows,
    theme: "grid",
    headStyles: {
      fillColor: [30, 41, 82],
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 9,
      cellPadding: 4,
    },
    bodyStyles: {
      fontSize: 8,
      cellPadding: 3,
    },
    alternateRowStyles: {
      fillColor: [245, 247, 250],
    },
    columnStyles: {
      0: { cellWidth: 80 },
    },
    didDrawPage() {
      drawHeaderBar(doc);
    },
  });

  // Score color legend
  const legendDoc = doc as JsPDFWithAutoTable;
  const legendY: number =
    legendDoc.lastAutoTable?.finalY ?? legendDoc.previousAutoTable?.finalY ?? 180;
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text(
    "Scores: Green \u226590 (Good)  |  Orange \u226550 (Needs Work)  |  Red <50 (Poor)",
    14,
    legendY + 10
  );

  // Add footers to all pages
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    drawFooter(doc, i, totalPages);
  }

  const filename = `lighthouse-report-${today}.pdf`;
  doc.save(filename);
  } catch (error) {
    console.error("Failed to export PDF:", error);
  }
}
